### PR TITLE
Split fulltext and site search indexes

### PR DESCRIPTION
**Pull request by varun-magesh**
This PR splits indexing and searching between site-wide metadata search and fulltext search of casebooks. This is expected to address indexing speed issues on staging.

### CODE REVIEW

**Comment by lizadaly** [comment]
I think the test harness needs the index process run at least once, judging from the errors?

**Comment by varun-magesh** [comment]
I think the setup in the doctests explicitly create the search index --- it must be failing for some reason; see e.g. models.py:933
```python
         >>> FullTextSearchIndex().create_search_index()
```

**Comment by varun-magesh** [comment]
Also --- _search is failing but casebook_fts (which depends on search) passes... huh.

**Comment by varun-magesh** [comment]
Oh I'm silly! nothing to do with indexing, just forgot to update test cases :-1:

**Review by bensteinberg — APPROVED** [review]
LGTM. I don't think I can comment in detail on the SQL or whether/how to do the inheritance. My proofreading eyes want to change "seperate" to "separate" several places in the SQL comments. Let's discuss elsewhere what to do with the existing cron job on stage before deployment.

**Comment by varun-magesh** [comment]
I just looked up 'seperate' and 'separate' and had no idea they were different --- oops! I probably made that error in a million undergrad papers.

**Pull request merged**
