### PR TITLE
Create a Casebook Plus Sign

### PR DESCRIPTION
**Pull request by shljessie**
Screen Shot 2022-06-22 at 4 29 25 PM

Adding a New Plus Sign Icon for the Create a Casebook.

### CODE REVIEW

**Comment by matteocargnelutti** [comment]
**Note:** Chatted with @shljessie about the opportunity of maybe using `<button>` and an SVG here to help with accessibility and scaling 😄.

**Comment by lizadaly** [comment]
I'm not familiar enough with the code to know for sure—does this button work? I'm guessing so but just checking!

**Comment by shljessie** [comment]
Yes it does! Im using the same line for the original create a casebook button. 
<button type="button" class="create-casebook-plus" data-action="show-casebook-modal"> </button>
don't know if there is a better way though!

**Comment by shljessie** [comment]
```
 <button type="button" class="create-casebook-plus" data-action="show-casebook-modal">
            </button>
```

**Review by lizadaly — APPROVED** [review]
Right on then! Once you merge the approved PR, in a minute or so it should end up on our staging environment at https://h2o-stage.lil.tools/, and we can spot-check it there too.

**Comment by rebeccacremona** [comment]
Remark from the peanut gallery: once this is a keyboard-accessible button, it is worth testing whether, if you use the new button to open the modal, if when you press escape, keyboard focus is set to the new button. I -think- the modal JS is smart enough for that to work correctly, but am not positive.

**Comment by lizadaly** [comment]
@rebeccacremona I tested it out on Chrome locally and it both receives keyboard focus when tabbing, then you can hit enter to open the modal, and when the modal is closed with ESC the focus is still on the new button.

**Comment by lizadaly** [comment]
I'm merging because of perms on the main repo.

**Pull request merged**
