### PR TITLE
Change "Search Inside" tab to "Find"

### PR DESCRIPTION
**Pull request by lizadaly**
Per @cath9: 

image

### CODE REVIEW

**Comment by lizadaly** [comment]
@cath9 Should the placeholder text also say "Find in <title>" instead of "Search in <title>"?

**Review by matteocargnelutti — APPROVED** [review]
👍

**Comment by cath9** [comment]
Very open to conflicting opinions, but I was imagining the tab would just say "Find".

**Comment by cath9** [comment]
Ignore the previous comment. Yes, the text in the field can say "Find in <title>"

**Comment by lizadaly** [comment]
image

**Pull request merged**
