### PR TITLE
adding create a casebook popup design changes

### PR DESCRIPTION
**Pull request by shljessie**
Screen Shot 2022-07-05 at 2 36 49 PM

Screen Shot 2022-07-05 at 2 40 24 PM

Added svgs for new icons on the popup page, not sure if this is the right way to make css changes though! 😊

### CODE REVIEW

**Comment by lizadaly** [comment]
This looks so nice!

Two things:

* It looks like most SVGs in the repo are distinct files referenced as background images (see `casebook.scss`). Could you do that here too, so the SVG code doesn't have to be inlined with the template?
* I think to keep it more consistent with the previous behavior we might want keep the word "Search" in the second option. What do you think about labelling it "Search for a Casebook to Customize"? Is that too long?

**Comment by shljessie** [comment]
Screen Shot 2022-07-05 at 3 59 30 PM
Added those changes! 😊

**Comment by lizadaly** [comment]
Much cleaner! Let's check with @rebeccacremona tomorrow to ensure those buttons are maximally accessible. I think for example we want to make an association between the text labels and the buttons themselves.

**Review by rebeccacremona — CHANGES_REQUESTED** [review]
This looks so nice!

Alas, we aren't supposed to nest buttons inside links. Since when you click, you are taken to a new destination, we do in fact want links here (links -> navigation; buttons -> trigger in-page actions), so that's good! But instead of the button inside, I think we just want a `<span>`. For good measure, you can made it a `<span aria-hidden="true">` so that screen readers know it's only an icon for decoration. Then this will be fully accessible.

**Review by rebeccacremona — APPROVED** [review]

**Pull request merged**
