### PR TITLE
Update to welcome email

### PR DESCRIPTION
**Pull request by cath9**

### CODE REVIEW

**Comment by holtchesley** [comment]
Looks like we had a test checking for some of the old copy. I'll fix that up when I get a chance.

**Comment by bensteinberg** [comment]
I believe this is a plain-text email, not HTML, so `<a>` and `<b>` tags won't work as is. I think we chose plain text over HTML mail as being more deliverable.

**Comment by cath9** [comment]
My bad. Deliverable as in won't get caught by filters?

**Comment by bensteinberg** [comment]
Not at all! Yeah, HTML in email is one of many signals that spam filters observe, but I don't know how heavily weighted it is, or whether its weight is conditioned on other signals, etc.

It's also possible that we made the decision on some other basis, like aesthetics or maintainability, or some combination.

**Comment by cath9** [comment]
After 20 minutes of Google research, it seems like there are some pros to plain text around delivery. So let me go back and see about making changes to the email to strip some formatting.

**Pull request closed without merging**
