### PR TITLE
Minimal change for upgrade to bullseye

### PR DESCRIPTION
**Pull request by bensteinberg**

### CODE REVIEW

**Comment by bensteinberg** [comment]
Merging this will probably need to wait for some updates to salt config.

**Comment by bensteinberg** [comment]
For future reference (?), the versions of the node file without the `deb` infix have a dependency on the package `python-minimal`, which does not exist in bullseye. This PR sets our node version to 16, which is LTS.

**Comment by bensteinberg** [comment]
I'm going to mark this ready for review; I don't anticipate a lot of changes to salt config (i.e. long wait for deployability), but if we think there's likely to be a bugfix or something requiring immediate deployment in the near future, we can hold on merging this.

**Comment by holtchesley** [comment]
Looks like this successfully ran the JS tests, and the node upgrade is the only think in it that would concern me. 👍

**Review by rebeccacremona — APPROVED** [review]
Same, LGTM! I saw this go by in the JS build, which is weird... If we notice JS peculiarities that weren't caught by the tests, we can pull that thread....
```
npm WARN old lockfile vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:743:9)
npm WARN old lockfile  Could not fetch metadata for vue-loader-v16@16.8.3 vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:743:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '16.8.3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '16.0.0-beta.5',
npm WARN old lockfile     '16.0.0-beta.5.1',
npm WARN old lockfile     '16.0.0-beta.5.2',
npm WARN old lockfile     '16.0.0-beta.5.3',
npm WARN old lockfile     '16.0.0-beta.5.4'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '16.0.0-beta.5.4' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
```

**Comment by bensteinberg** [comment]
Thanks, @holtchesley and @rebeccacremona. I'm going to merge this -- I expect auto-deploy to stage will fail, but that I'll be able to spin up new bullseye minions and replace the old ones in the load balancer.

**Comment by bensteinberg** [comment]
(I tell a lie - this should deploy OK to stage, and spinning up new bullseye minions should also work.)

**Pull request merged**
