### PR TITLE
Restore playwright; upgrade black

### PR DESCRIPTION
**Pull request by bensteinberg**
This PR restores playwright to `requirements.in`, as we need it for functional tests; it also unpins and upgrades `black` and lets it make some changes.

https://github.com/psf/black/blob/main/CHANGES.md#2430

### CODE REVIEW

**Review by rebeccacremona — APPROVED** [review]
Hmmm, does this mean the functional tests aren't currently run by Github Actions? Interesting, I didn't realize that.

**Comment by bensteinberg** [comment]
> Hmmm, does this mean the functional tests aren't currently run by Github Actions? Interesting, I didn't realize that.

I think they are running!

**Comment by rebeccacremona** [comment]
I must be confused. If playwright is necessary for functional tests, and functional tests are run in Github Actions, and we removed playwright in an earlier PR... I would have expected to see the tests fail. Since we didn't... I'm confused.

**Comment by bensteinberg** [comment]
Could playwright be built in to the runner?

**Pull request merged**
