### PR TITLE
Include links in full-text search

### PR DESCRIPTION
**Pull request by varun-magesh**
Include links in full text search; this completes the types of items that should be included in fts. No noticeable slowdown from adding text content.

This PR depends on PR #1601 and closes issue #1599.

### CODE REVIEW

**Comment by lizadaly** [comment]
Could you rebase `develop` from upstream on top of this? Looks like this includes the previous PR's changes too.

**Comment by varun-magesh** [comment]
So, I think this might be tricky.

This PR depends in part on changes from #1601, and couldn't be a standalone changeset without replicating code from #1601. I *think* that if #1601 is merged, then this one will update to show the right changes that are unique to this PR. If not, I could rebase to `develop` then. I think that if I rebase to develop now, it will be creating a bunch of extra work --- work to seperate this one from #1601, and then more work late to merge them back together.

I think the best options are:
1. Merge #1601, rebase/deal with this PR later.
2. Consolidate these changes and messages into #1601 (or vice versa) and merge them into `develop` as one PR.

**Comment by lizadaly** [comment]
Oh, you're right, I forgot it hadn't merged.

**Review by lizadaly — APPROVED** [review]

**Comment by varun-magesh** [comment]
Okay, looks like Git automatically handled the overlapping commits after I merged! This PR should be ready to go now as well.

**Pull request merged**
