### PR TITLE
Correct contact email address; fix a couple typos.

### PR DESCRIPTION
**Pull request by rebeccacremona**

### CODE REVIEW

**Comment by bensteinberg** [comment]
Want to change the email addresses in app/views/pages/privacy-policy.html.erb and app/views/pages/terms-of-service.html.erb?

**Comment by rebeccacremona** [comment]
Whoops. Yep.

**Comment by bensteinberg** [comment]
I also see an h2o.law URL in app/views/notifier/playlist_push_completed.erb, but I bet we're not using that anymore.

**Comment by rebeccacremona** [comment]
I'm not going to change `app/views/notifier/playlist_push_completed.erb` because we should probably delete that file....

**Pull request merged**
