### PR TITLE
Tweaks suggested by node debugging process

### PR DESCRIPTION
**Pull request by rebeccacremona**
This PR has a few tweaks suggested by the explorations in https://github.com/harvard-lil/h2o/issues/744 and https://github.com/harvard-lil/h2o/issues/743.

1) It suppresses some of the automatic calls to `yarn install`.

If merged, stage/prod deployments should be altered to include an explicit call to `yarn install --frozen-lockfile --check-files`. This command defaults to `NODE_ENV=development`; if you want only production requirements installed, set `NODE_ENV=production`.

2) It sets Travis to compile assets without the assistance of Spring, to prevent unwanted output and prevent spurious reports that asset compilation has failed. 

3) It adds, in comments, another option for suppressing unwanted output locally. If stage/prod calls to `precompile:assets`, which do not (should not!) use Spring, are spuriously reporting failed compilation, we can consider uncommenting one or both lines.

Both the above issues are still pending; I'll keep my eye on them.

### CODE REVIEW

**Comment by bensteinberg** [comment]
In the new scheme, on stage and prod, does it make a difference whether we run 
```
rake assets:clean
rake assets:precompile
NODE_ENV=production yarn install --frozen-lockfile --check-files
```
or
```
rake assets:clean
NODE_ENV=production yarn install --frozen-lockfile --check-files
rake assets:precompile
```
?

**Comment by rebeccacremona** [comment]
Yes. `yarn install` needs to be run before anything node-related is used, so either:
```
rake assets:clean
NODE_ENV=production yarn install --frozen-lockfile --check-files
rake assets:precompile
```
or
```
NODE_ENV=production yarn install --frozen-lockfile --check-files
rake assets:clean
rake assets:precompile
```

**Comment by bensteinberg** [comment]
I'll rebase and merge this tomorrow, after I've tuned up the salt config appropriately.

**Comment by bensteinberg** [comment]
This looks good. On stage, with the new salt config, the output of `NODE_ENV=production yarn install --frozen-lockfile --check-files` is
```
                       warning "vue-jest > ts-jest@23.10.5" has incorrect peer dependency "jest@>=22 <24".
                        yarn install v1.15.2
                        [1/4] Resolving packages...
                        [2/4] Fetching packages...
                        info fsevents@1.2.7: The platform "linux" is incompatible with this module.
                        info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
                        [3/4] Linking dependencies...
                        [4/4] Building fresh packages...
                        Done in 6.00s.
 ```
and the output of `rake assets:precompile` is
```
                        Skipping webpacker:yarn_install
                        Skipping yarn:install
                        Compiling…
                        Compiled all packs in /usr/local/share/h2o/public/packs
```

**Pull request merged**
